# Generated by Django 5.2.7 on 2025-10-06 09:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('formating_style', models.CharField(choices=[('apa', 'APA'), ('mla', 'MLA'), ('harvard', 'Harvard'), ('chicago', 'Chicago'), ('oscola', 'OSCOLA')], default='apa', max_length=120)),
                ('assignment_type', models.CharField(choices=[('essay', 'Essay'), ('dissertation', 'Dissertation'), ('proposal', 'Proposal'), ('term_paper', 'Term Paper')], max_length=120)),
                ('pages', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('revision', 'Revision'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('paid', 'Paid')], max_length=120)),
                ('amount_per_page', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('due_date', models.DateTimeField()),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed_by', to=settings.AUTH_USER_MODEL)),
                ('new_writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_orders', to=settings.AUTH_USER_MODEL)),
                ('old_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_writer_history', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='manage_orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision', to='manage_orders.order')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
