# Generated by Django 5.2.7 on 2025-10-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('assigned', 'Assigned'), ('revision', 'Revision'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('paid', 'Paid')], default='available', max_length=120),
        ),
    ]
