# Generated by Django 5.2.7 on 2025-10-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_orders', '0003_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount_per_page',
            field=models.FloatField(default=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
